# User model for the database, defines the structure of the 'users' table and its fields
from sqlalchemy import Column, Integer, String, Boolean, DateTime
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.session import Base

class User(Base):
    """SQLAlchemy ORM model representing system users (Doctors, Staff, Admins)."""
    __tablename__ = "users"

    # Unique identity column for each user
    id = Column(Integer, primary_key=True, index=True)
    
    # User credentials
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    
    # Profile information
    full_name = Column(String, nullable=False)
    
    # Account status & access level
    is_active = Column(Boolean, default=True)
    is_superuser = Column(Boolean, default=False)
    
    # Audit timestamp automatically generated by PostgreSQL
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    memberships = relationship("ClinicMembership", back_populates="user")
