"""create clinic membership tables

Revision ID: a807f733a8e3
Revises: 71eda1fd3061
Create Date: 2026-09-23 20:33:35.940839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a807f733a8e3'
down_revision: Union[str, None] = '71eda1fd3061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)
    op.create_table('clinic_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'clinic_id', name='uq_clinic_memberships_user_id_clinic_id')
    )
    op.create_index(op.f('ix_clinic_memberships_id'), 'clinic_memberships', ['id'], unique=False)
    op.create_table('membership_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'DOCTOR', 'SECRETARY', name='membership_role'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['clinic_memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'role', name='uq_membership_roles_membership_id_role')
    )
    op.create_index(op.f('ix_membership_roles_id'), 'membership_roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_roles_id'), table_name='membership_roles')
    op.drop_table('membership_roles')
    postgresql.ENUM(name='membership_role').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_clinic_memberships_id'), table_name='clinic_memberships')
    op.drop_table('clinic_memberships')
    op.drop_index(op.f('ix_clinics_id'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
